version: "3"
services:
  web:
    environment:
      LABEL_SERVICE_EXTERNAL_PATH: ${LABEL_SERVICE_EXTERNAL_PATH}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    build: .
    ports:
      - "3000:3000"